import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    container: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        backgroundColor: '#09263D',
    },
    screenTitle: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: 15,
        fontFamily: 'Rajdhani-Bold',
        fontSize: 22,
        color: '#f6f4eb',
    },
    contador: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        fontFamily: 'Rajdhani-Medium',
        fontSize: 48,
        color: '#f6f4eb',
    },
    finalizados: {
        display: 'flex',
        flexDirection: 'column',
        paddingHorizontal: 15,
    },
    finalizadosTitle: {
        display: 'flex',
        flexDirection: 'row',
        paddingTop: 15,
        fontFamily: 'Rajdhani-Bold',
        fontSize: 22,
        color: '#f6f4eb',
    },
    finalizadoArea: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    finalizadosItem: {
        display: 'flex',
        flexDirection: 'row',
        marginVertical: 5,
        fontFamily: 'Rajdhani-Medium',
        fontSize: 20,
        color: '#f6f4eb',
    },
    exercises: {
      display: 'flex',
      flexDirection: 'column',
      paddingHorizontal: 15,
    },
    exercisesArea: {
      display: 'flex',
      flexDirection: 'column',
      marginVertical: 15,
    },
    exercisesName: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 5,
    },
    exercisesText: {
      fontFamily: 'Rajdhani-Bold',
      fontSize: 22,
      color: '#f6f4eb',
    },
    exerciseDescription: {
      fontFamily: 'Rajdhani-Medium',
      fontSize: 20,
      color: '#f6f4eb',
      padding: 0,
    },
    btnDefault: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      margin: 15,
    },
    btnText: {
      fontFamily: 'Rajdhani-Bold',
      fontSize: 20,
      color: '#f6f4eb',
      backgroundColor: '#970A44',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 5,
    },
})